CREATE TABLE tickets (
  id INT NOT NULL,
  category_codeName VARCHAR(255) NOT NULL,
  category_name VARCHAR(255) NOT NULL,
  category_description VARCHAR(255) NOT NULL,
  category_emoji VARCHAR(255) NOT NULL,
  category_color VARCHAR(255) NOT NULL,
  category_categoryId VARCHAR(255) NOT NULL,
  category_ticketNameOption VARCHAR(255) NOT NULL,
  category_customDescription TEXT NOT NULL,
  category_cantAccess TEXT NOT NULL,
  category_askQuestions BOOLEAN NOT NULL,
  category_questions TEXT NOT NULL,
  creator VARCHAR(255) NOT NULL,
  invited TEXT NOT NULL,
  createdAt BIGINT NOT NULL,
  claimed BOOLEAN NOT NULL,
  claimedBy INT NOT NULL,
  claimedAt BIGINT NOT NULL,
  closed BOOLEAN NOT NULL,
  closedBy VARCHAR(255) NOT NULL,
  closedAt BIGINT NOT NULL,
  messageId VARCHAR(255) NOT NULL,
  closeReason VARCHAR(255) NOT NULL,
  transcriptURL VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);